version: '3'

services:
    nginx:
        image: ghcr.io/getimages/nginx:1.23.3-alpine
        restart: always
        working_dir: /app
        volumes:
            - ./:/app
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/logs/:/var/log/nginx/
        ports:
            - ${APP_EXPOSED_PORT:-0}:80
        depends_on:
            - php
        networks:
            - reverb-example-network

    php:
        build: docker/php
        image: my_php
        restart: always
        working_dir: /app
        volumes:
            - ./:/app/
        depends_on:
            - db
        ports:
            - "8080:8080" #reverb port
        networks:
            - reverb-example-network

    db:
        image: mysql:latest
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        ports:
            - "33006:3306"
        networks:
            - reverb-example-network

    pma:
        image: phpmyadmin:latest
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=${DB_HOST}
            #- PMA_USER=${DB_USERNAME}
            #- PMA_PASSWORD=${DB_PASSWORD}
            - PMA_PORT=${DB_PORT}
            - UPLOAD_LIMIT= 64M
        depends_on:
            - db
        ports:
            - "9088:80"
        networks:
            - reverb-example-network

volumes:
    dbdata:
        driver: local

networks:
    reverb-example-network:
        driver: bridge
